name: Trigger auto deployment for dummy-sample-6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dummy-sample-6-AutoDeployTrigger-421cb267-2537-4c26-8513-e440e3c0b2c4.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DUMMYSAMPLE6_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.DUMMYSAMPLE6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DUMMYSAMPLE6_REGISTRY_PASSWORD }}
          containerAppName: dummy-sample-6
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/dummy-sample-6:${{ github.sha }}
          

     

